version: '3.2'

services:
  db:
    image: datosgobar/portal-geoandino-postgres:0.2.1
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - DATASTORE_DB
    networks:
      main:
  geonode:
    image: datosgobar/portal-geoandino:0.2.1
    environment:
      - ALLOWED_HOST_IP
      - ALLOWED_HOST
      - SITEURL
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_HOST=db
      - DATASTORE_DB
    networks:
      main:
    depends_on:
      - db
    ports:
      - "80:80"
  geonetwork:
    image: datosgobar/portal-geoandino-geonetwork:0.2.1
    networks:
      main:
  geoserver:
    image: datosgobar/portal-geoandino-geoserver:0.2.1
    networks:
      main:

networks:
  main:
