---

- name: Update directory permissions
  file:
    path: "{{ geoandino_app }}"
    owner: geonode
    group: www-data
    recurse: yes
    mode: 0777

# TODO: Remove this tasks. If a new sub-app is added, you need to add a new line here

- name: Remove execution permission from tests
  file:
    path: "{{ item }}"
    recurse: yes
    mode: 0666
  with_items:
    - "{{ geoandino_app }}tests/"
    - "{{ geoandino_app }}apps/datajsonar/tests/"

- name: Create upload directories
  file:
    path: "{{ item }}"
    state: directory
    owner: geonode
    group: www-data
    mode: 0777
    recurse: yes
  with_items:
    - "{{ media_dir }}thumbs"
    - "{{ media_dir }}layer"


- name: Change static owner and group
  file:
    path: "{{ static_dir }}"
    owner: www-data
    group: www-data
    recurse: yes
    state: directory
