---

- name: Add geonode user
  user:
    name: geonode
    comment: "Geonode application user"

- name: Add server run scripts
  template:
    src: "bins/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: u+x,g+x,o+x
  with_items:
    - run_server.sh

- import_tasks: requirements.yml

- name: Clone geoandino theme
  git:
    repo: 'https://github.com/datosgobar/geoandino-theme.git'
    dest: /home/geonode/geoandino
    version: "{{ geoandino_version }}"

- name: Install geoandino production requirements
  pip:
    requirements: "{{ geoandino_dir }}requirements.txt"

- import_tasks: configure_apache.yml
- import_tasks: configure_app.yml
- import_tasks: configure_permissions.yml
