---

- name: Install requirements
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - wget
    - vim

- name: Get geoserver.war
  get_url:
    url: http://build.geonode.org/geoserver/latest/geoserver-{{ geoserver_version }}.war
    dest: "{{ webapps_dir }}geoserver.war"


- name: Generate geoserver files
  shell: sh /entrypoint.sh
  async: 15
  poll: 0

- name: wait for file web.xml is created
  wait_for:
    path: "{{ web_xml_file }}"

- name: Add geonode GEONODE_BASE_URL
  blockinfile:
    path: "{{ web_xml_file }}"
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    insertafter: "<display-name>GeoServer</display-name>"
    content: |
      <context-param>
        <param-name>GEONODE_BASE_URL</param-name>
        <param-value>http://{{ geonode_host }}/</param-value>
      </context-param>

- name: Add baseUrl in geonode auth provider
  lineinfile:
    path: "{{ config_xml_file }}"
    regexp: '.*baseUrl.*'
    line: '<baseUrl>http://{{ geonode_host }}/</baseUrl>'

- name: Add IGN to allowed to print hosts
  blockinfile:
    path: "{{ printing_xml_file }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    insertbefore: '- !localMatch'
    content: |2
        - !dnsMatch
          host: wms.ign.gob.ar
          port: 80
    