---

- name: Get geonode
  git:
    repo: https://github.com/GeoNode/geonode.git
    dest: "{{ geonode_dir }}"
    version: 2.6.x
    depth: 10

- name: Install python requirements
  pip:
    name: "{{ geonode_dir }}"

- name: Change project owner
  file:
    path: "{{ geonode_dir }}"
    owner: geonode
    state: directory
    recurse: yes