---

- name: Clone geoandino theme
  git:
    repo: 'https://github.com/datosgobar/geoandino-theme.git'
    dest: /home/geonode/geoandino
    version: master

- include: configure_apache.yml
- include: configure_app.yml
- include: configure_permissions.yml
