---

- name: Ensure conf and bins directory
  file:
    path: "{{ item }}"
    state: directory
  become_user: geonode
  with_items:
    - "{{ configuration_dir }}"
    - "{{ bins_dir }}"

- name: Add link settings script
  template:
    src: bins/link_settings.sh
    dest: "{{ bins_dir }}link_settings.sh"
    mode: 0770
    owner: geonode
    group: geonode

- name: Copy django settings file
  template:
    src: conf/local_settings.py
    dest: "{{ settings_file }}"
  become_user: geonode

- name: Create configuration link
  shell: "{{ bins_dir }}link_settings.sh"

- name: Run collect static
  shell: python manage.py collectstatic --noinput
  args:
    chdir: "{{ custom_dir }}"
  become_user: geonode