---

- name: Update directory permissions
  file:
    path: "{{ custom_dir }}"
    owner: geonode
    group: www-data
    recurse: yes
    mode: 0777

- name: Create upload directories
  file:
    path: "{{ item }}"
    state: directory
    owner: geonode
    group: www-data
    mode: 0777
    recurse: yes
  with_items:
    - "{{ media_dir }}thumbs"
    - "{{ media_dir }}layer"


- name: Change static owner and group
  file:
    path: "{{ static_dir }}"
    owner: www-data
    group: www-data
    recurse: yes
    state: directory